In [1]:
import numpy as np
import pandas as pd

### Numpy problems

#### 1. Using NumPy, create a 1D array of 20 random integers between 10 and 50. Then, fi nd the mean and standard deviation of the array.

In [2]:
A=np.random.randint(10,50,20,dtype=int)

In [3]:
print(f'The random array is {A}')

The random array is [29 46 44 48 15 38 20 24 45 26 15 31 25 33 37 19 16 37 49 45]


In [4]:
stdev_A=np.std(A)
mean_A=np.mean(A)
print(f'The standard deviation of A is {stdev_A}')
print(f'The mean of A is {mean_A}')

The standard deviation of A is 11.436345570154831
The mean of A is 32.1


#### 2 .Create a 2D NumPy array of shape (6, 5) fi lled with random fl oats between 0 and 1. Reshape this array to have shape (5, 6) and print both the original and reshaped arrays.

In [5]:
B=np.random.rand(6,5)
print(f'The array is {B}')

The array is [[0.3963519  0.74376628 0.61475442 0.31340992 0.91475297]
 [0.31134646 0.76820506 0.01307104 0.98704408 0.06601411]
 [0.73226876 0.60081083 0.59013006 0.81693968 0.38415416]
 [0.11616337 0.7006665  0.36893485 0.15282007 0.16559288]
 [0.18823023 0.2987137  0.64349433 0.19880192 0.68586902]
 [0.69822635 0.33672714 0.05027765 0.59868257 0.78267548]]


In [6]:
B_reshaped=B.reshape(5,6)
print(f'Reshaped array is {B_reshaped}')

Reshaped array is [[0.3963519  0.74376628 0.61475442 0.31340992 0.91475297 0.31134646]
 [0.76820506 0.01307104 0.98704408 0.06601411 0.73226876 0.60081083]
 [0.59013006 0.81693968 0.38415416 0.11616337 0.7006665  0.36893485]
 [0.15282007 0.16559288 0.18823023 0.2987137  0.64349433 0.19880192]
 [0.68586902 0.69822635 0.33672714 0.05027765 0.59868257 0.78267548]]


#### 3.Create a 2D array of shape (5, 5) fi lled with numbers from 1 to 25. Extract a subarray that includes rows 2 to 4 and columns 1 to 3.

In [7]:
C=np.arange(1,26).reshape(5,5)
print(f'The 2D array is {C}')

The 2D array is [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [8]:
C_extracted=C[1:4,0:3]
print(f'The extracted subarray is {C_extracted}')

The extracted subarray is [[ 6  7  8]
 [11 12 13]
 [16 17 18]]


#### 4. Generate two 1D arrays A and B, each containing 10 random integers between 1 and 100. Add the arrays together, then multiply the result by 2. Show the results of each operation.

In [9]:
A=np.random.randint(1,100,10)
B=np.random.randint(1,100,10)
print(f'The first array is {A}')
print(f'The second array is {B}')      

The first array is [76 71 56 96 22 43 43 74 87 66]
The second array is [87 40  4 87  1 30 13 32 68 53]


In [10]:
sum_of_arrays = A+B
print(f'The sum of arrays A and B is {sum_of_arrays}')

The sum of arrays A and B is [163 111  60 183  23  73  56 106 155 119]


In [11]:
multiplied_result=sum_of_arrays*2
print(f'The sum of arrays when multiplied by 2 is {multiplied_result}')

The sum of arrays when multiplied by 2 is [326 222 120 366  46 146 112 212 310 238]


#### 5. Create a 2D array A of shape (3, 4) fi lled with random integers between 1 and 10. Create a 1D array B of shape (4,) with values [1, 2, 3, 4]. Add the 1D array to the 2D array and explain how broadcasting works in this case.

In [45]:
A=np.random.randint(1,10,(3,4))
B=np.arange(1,5)
print(f'The 2D array is {A}')
print(f'The 1D array is {B}')

The 2D array is [[7 7 9 6]
 [2 4 3 3]
 [6 6 5 5]]
The 1D array is [1 2 3 4]


In [46]:
broadcasted_array=A+B
print(f'The broadcasted array is {broadcasted_array}')

The broadcasted array is [[ 8  9 12 10]
 [ 3  6  6  7]
 [ 7  8  8  9]]


In [47]:
# Broadcasting simplifies mathematical operations on arrays with different shapes.
# It enables numpy to efficiently apply operations element-wise without explicitly copying or reshaping data.

#### 6. Create a 3x3 matrix of random integers between 1 and 100. Find the row with the maximum sum, and then the maximum value in that row.

In [15]:
A=np.random.randint(1,101,size=(3,3))
print(f'The 3x3 matrix is {A}')

The 3x3 matrix is [[21 90 45]
 [40 40 35]
 [64 90 16]]


In [16]:
max_sum_rows=np.sum(A,axis=1)
max_value_row_index=np.argmax(max_sum_rows)
max_value_in_maxsum_row=np.max(A[max_value_row_index])

In [17]:
print(f'The sum of rows are {max_sum_rows}')
print(f'The max value in the maximum sum row which is row {max_value_row_index} is {max_value_in_maxsum_row}')

The sum of rows are [156 115 170]
The max value in the maximum sum row which is row 2 is 90


#### 7. Create two 2D arrays A and B, both of shape (2, 2), fi lled with random integers. Compute the matrix multiplication of A and B using np.dot().

In [18]:
A=np.random.randint(1,50,size=(2,2))
B=np.random.randint(1,50,size=(2,2))

In [19]:
print(f'The first 2D array is {A}')
print(f'The second 2D array is {B}')

The first 2D array is [[26 12]
 [ 6 38]]
The second 2D array is [[23  6]
 [36 18]]


In [20]:
dot_product_A_B=np.dot(A,B)
print(f'The dot product of A and B is {dot_product_A_B}')

The dot product of A and B is [[1030  372]
 [1506  720]]


#### 8. Create an array of shape (6, 6) with random integers between 1 and 50. Using boolean indexing, extract all values greater than 25.

In [21]:
A=np.random.randint(1,50,size=(6,6))
print(f'The random array is {A}')

The random array is [[40 40 43 34 38 10]
 [33  3 28 39  7 28]
 [47 42 31  4 32 35]
 [ 1 27 42 41 17 49]
 [19  7 41 25 33  9]
 [44 24  7 33 16 43]]


In [22]:
A_greater_than_25 =A[A>25]
print(f'The array with numbers greater than 25 is {A_greater_than_25}')

The array with numbers greater than 25 is [40 40 43 34 38 33 28 39 28 47 42 31 32 35 27 42 41 49 41 33 44 33 43]


#### 9. Create a 5x5 array of random fl oats between 0 and 1. Calculate the median and variance along the columns and rows separately.

In [23]:
A=np.random.rand(5,5)
print(f'The random array is {A}')

The random array is [[0.16799358 0.00297533 0.46103618 0.81377938 0.65447306]
 [0.68082321 0.29871551 0.41745814 0.01071805 0.79565975]
 [0.2355427  0.31038522 0.56562527 0.88109367 0.89013877]
 [0.45336785 0.67136625 0.3224936  0.15336935 0.30420795]
 [0.24365577 0.6214032  0.48029182 0.78740083 0.00905872]]


In [24]:
A_row_mean=np.mean(A,axis=1)
A_column_mean=np.mean(A,axis=0)
A_row_variance=np.var(A,axis=1)
A_column_variance=np.var(A,axis=0)

print(f'The mean of rows are {A_row_mean}')
print(f'The mean of columns are {A_column_mean}')
print(f'The variance of rows are {A_row_variance}')
print(f'The variance of rows are {A_column_variance}')

The mean of rows are [0.42005151 0.44067493 0.57655713 0.380961   0.42836207]
The mean of columns are [0.35627662 0.3809691  0.449381   0.52927225 0.53070765]
The variance of rows are [0.08982812 0.07784797 0.07566676 0.03013708 0.07576042]
The variance of rows are [0.03549357 0.05935322 0.00634471 0.13631089 0.10762559]


#### 10. Generate a 3x3 matrix of random integers between 1 and 10. Perform the following element-wise operations: subtract 2 from each element, square each element, and compute the reciprocal of each element.

In [25]:
A=np.random.randint(1,10,size=(3,3))
print(f'The random array is {A}')

The random array is [[1 7 9]
 [5 7 9]
 [9 1 8]]


In [140]:
sub_A=A-2
square_A=A^2
reciprocal_A=np.reciprocal(A.astype(float))

print(f'The array subtracted by 2 is {sub_A}')
print(f'The square of array is {square_A}')
print(f'The reciprocal of array is {reciprocal_A}')


The array subtracted by 2 is [[5 5 7 4]
 [0 2 1 1]
 [4 4 3 3]]
The square of array is [[ 5  5 11  4]
 [ 0  6  1  1]
 [ 4  4  7  7]]
The reciprocal of array is [[0.14285714 0.14285714 0.11111111 0.16666667]
 [0.5        0.25       0.33333333 0.33333333]
 [0.16666667 0.16666667 0.2        0.2       ]]


# ---------------------------------------------------------------------------------------------------------------

### Pandas Problems

#### 1. Basic Exploration Load the dataset into a Pandas DataFrame. Display:
○ The first 10 rows
○ The total number of rows and columns
○ Summary statistics for numerical columns

In [169]:
df=pd.read_csv("auto-mpg.csv")

In [170]:
# The first 10 rows
df.head(10)

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   
5  15.0          8         429.0        198    4341          10.0          70   
6  14.0          8         454.0        220    4354           9.0          70   
7  14.0          8         440.0        215    4312           8.5          70   
8  14.0          8         455.0        225    4425          10.0          70   
9  15.0          8         390.0        190    3850           8.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino  
5       1           ford galaxie 500  
6       1           chevrolet impala  
7       1          plymouth fury iii  
8       1           pontiac catalina  
9       1         amc ambassador dpl

In [171]:
df.shape
print(f'The number of rows is {df.shape[0]}')
print(f'The number of columns is {df.shape[1]}')

The number of rows is 398
The number of columns is 9


In [172]:
print(f"Summary statistics for numerical columns is: ")
df.describe()

Summary statistics for numerical columns is: 


mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

#### 2. Filtering and Indexing Find all cars manufactured in 1975 with a weight less than 3000. Return the DataFrame with selected columns: car_name, weight, and mpg.

In [173]:
filtered_df=df[(df["model year"]==1975) & (df["weight"]<3000)][["car name","weight","mpg"]]
print(filtered_df)

Empty DataFrame
Columns: [car name, weight, mpg]
Index: []


#### 3. Handling Missing Data Identify if there are any missing values in the dataset. Replace missing values in the horsepower column with the column's median.

In [174]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object 
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   car name      398 non-null    object 
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB


In [175]:
df['horsepower'].unique()

array(['130', '165', '150', '140', '198', '220', '215', '225', '190',
       '170', '160', '95', '97', '85', '88', '46', '87', '90', '113',
       '200', '210', '193', '?', '100', '105', '175', '153', '180', '110',
       '72', '86', '70', '76', '65', '69', '60', '80', '54', '208', '155',
       '112', '92', '145', '137', '158', '167', '94', '107', '230', '49',
       '75', '91', '122', '67', '83', '78', '52', '61', '93', '148',
       '129', '96', '71', '98', '115', '53', '81', '79', '120', '152',
       '102', '108', '68', '58', '149', '89', '63', '48', '66', '139',
       '103', '125', '133', '138', '135', '142', '77', '62', '132', '84',
       '64', '74', '116', '82'], dtype=object)

In [176]:
hp=df[(df['horsepower']!='?')]['horsepower'].astype(int).median()
print(hp)

93.5


In [177]:
df['horsepower'].unique()

array(['130', '165', '150', '140', '198', '220', '215', '225', '190',
       '170', '160', '95', '97', '85', '88', '46', '87', '90', '113',
       '200', '210', '193', '?', '100', '105', '175', '153', '180', '110',
       '72', '86', '70', '76', '65', '69', '60', '80', '54', '208', '155',
       '112', '92', '145', '137', '158', '167', '94', '107', '230', '49',
       '75', '91', '122', '67', '83', '78', '52', '61', '93', '148',
       '129', '96', '71', '98', '115', '53', '81', '79', '120', '152',
       '102', '108', '68', '58', '149', '89', '63', '48', '66', '139',
       '103', '125', '133', '138', '135', '142', '77', '62', '132', '84',
       '64', '74', '116', '82'], dtype=object)

In [178]:
hps=df['horsepower'].values
hps[hps=='?']=hp

In [179]:
df['horsepower']=hps.astype(int)

In [180]:
# The non numeric values in "horsepower" has been replaced with median

In [181]:
df['horsepower'].unique()

array([130, 165, 150, 140, 198, 220, 215, 225, 190, 170, 160,  95,  97,
        85,  88,  46,  87,  90, 113, 200, 210, 193,  93, 100, 105, 175,
       153, 180, 110,  72,  86,  70,  76,  65,  69,  60,  80,  54, 208,
       155, 112,  92, 145, 137, 158, 167,  94, 107, 230,  49,  75,  91,
       122,  67,  83,  78,  52,  61, 148, 129,  96,  71,  98, 115,  53,
        81,  79, 120, 152, 102, 108,  68,  58, 149,  89,  63,  48,  66,
       139, 103, 125, 133, 138, 135, 142,  77,  62, 132,  84,  64,  74,
       116,  82])

#### 4. Data Transformation Add a new column power_to_weight_ratio, calculated as horsepower / weight.

In [182]:
df["power_to_weight_ratio"]=df["horsepower"]/df["weight"]

In [183]:
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0         130    3504          12.0   
1  15.0          8         350.0         165    3693          11.5   
2  18.0          8         318.0         150    3436          11.0   
3  16.0          8         304.0         150    3433          12.0   
4  17.0          8         302.0         140    3449          10.5   

   model year  origin                   car name  power_to_weight_ratio  
0          70       1  chevrolet chevelle malibu               0.037100  
1          70       1          buick skylark 320               0.044679  
2          70       1         plymouth satellite               0.043655  
3          70       1              amc rebel sst               0.043694  
4          70       1                ford torino               0.040591

#### 5. Group By Group the cars by origin and calculate the mean mpg for each group.

In [184]:
df_grouped=df.groupby(by="origin")

In [185]:
df_grouped.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0   18.0          8         307.0         130    3504          12.0   
1   15.0          8         350.0         165    3693          11.5   
2   18.0          8         318.0         150    3436          11.0   
3   16.0          8         304.0         150    3433          12.0   
4   17.0          8         302.0         140    3449          10.5   
14  24.0          4         113.0          95    2372          15.0   
18  27.0          4          97.0          88    2130          14.5   
19  26.0          4          97.0          46    1835          20.5   
20  25.0          4         110.0          87    2672          17.5   
21  24.0          4         107.0          90    2430          14.5   
22  25.0          4         104.0          95    2375          17.5   
23  26.0          4         121.0         113    2234          12.5   
29  27.0          4          97.0          88    2130          14.5   
31  25.0          4         113.0          95    2228          14.0   
53  31.0          4          71.0          65    1773          19.0   

    model year  origin                      car name  power_to_weight_ratio  
0           70       1     chevrolet chevelle malibu               0.037100  
1           70       1             buick skylark 320               0.044679  
2           70       1            plymouth satellite               0.043655  
3           70       1                 amc rebel sst               0.043694  
4           70       1                   ford torino               0.040591  
14          70       3         toyota corona mark ii               0.040051  
18          70       3                  datsun pl510               0.041315  
19          70       2  volkswagen 1131 deluxe sedan               0.025068  
20          70       2                   peugeot 504               0.032560  
21          70       2                   audi 100 ls               0.037037  
22          70       2                      saab 99e               0.040000  
23          70       2                      bmw 2002               0.050582  
29          71       3                  datsun pl510               0.041315  
31          71       3                 toyota corona               0.042639  
53          71       3           toyota corolla 1200               0.036661

In [189]:
df_grouped_mean=df.groupby(by="origin")['mpg'].mean()

In [190]:
print(df_grouped_mean)

origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64


#### 6. Sorting Sort the DataFrame by mpg in descending order and display the top 10 cars with the highest mpg.

In [192]:
df_mpg_sort=df.sort_values(by='mpg',ascending=False)

In [200]:
df_mpg_sort.head(10)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
322  46.6          4          86.0          65    2110          17.9   
329  44.6          4          91.0          67    1850          13.8   
325  44.3          4          90.0          48    2085          21.7   
394  44.0          4          97.0          52    2130          24.6   
326  43.4          4          90.0          48    2335          23.7   
244  43.1          4          90.0          48    1985          21.5   
309  41.5          4          98.0          76    2144          14.7   
330  40.9          4          85.0          93    1835          17.3   
324  40.8          4          85.0          65    2110          19.2   
247  39.4          4          85.0          70    2070          18.6   

     model year  origin                         car name  \
322          80       3                        mazda glc   
329          80       3              honda civic 1500 gl   
325          80       2             vw rabbit c (diesel)   
394          82       2                        vw pickup   
326          80       2               vw dasher (diesel)   
244          78       2  volkswagen rabbit custom diesel   
309          80       2                        vw rabbit   
330          80       2             renault lecar deluxe   
324          80       3                       datsun 210   
247          78       3                   datsun b210 gx   

     power_to_weight_ratio  
322               0.030806  
329               0.036216  
325               0.023022  
394               0.024413  
326               0.020557  
244               0.024181  
309               0.035448  
330               0.050681  
324               0.030806  
247               0.033816

#### 7. Apply this function to each row and store the result in the new column.

In [204]:
def performance_score(row):
    return row['mpg'] * row['acceleration'] / row['weight']

In [207]:
df['performance_score']=df.apply(performance_score,axis=1)
df[['mpg','acceleration','weight','performance_score']].head()

mpg  acceleration  weight  performance_score
0  18.0          12.0    3504           0.061644
1  15.0          11.5    3693           0.046710
2  18.0          11.0    3436           0.057625
3  16.0          12.0    3433           0.055928
4  17.0          10.5    3449           0.051754

In [208]:
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0         130    3504          12.0   
1  15.0          8         350.0         165    3693          11.5   
2  18.0          8         318.0         150    3436          11.0   
3  16.0          8         304.0         150    3433          12.0   
4  17.0          8         302.0         140    3449          10.5   

   model year  origin                   car name  power_to_weight_ratio  \
0          70       1  chevrolet chevelle malibu               0.037100   
1          70       1          buick skylark 320               0.044679   
2          70       1         plymouth satellite               0.043655   
3          70       1              amc rebel sst               0.043694   
4          70       1                ford torino               0.040591   

   performance_score  
0           0.061644  
1           0.046710  
2           0.057625  
3           0.055928  
4           0.051754

#### 8. Visualization Preparation Generate a summary DataFrame with:
○ Average mpg, weight, and horsepower for each model_year.

In [211]:
df_summary_mpg_weight_horsepower=df.groupby("model year")[["mpg", "weight", "horsepower"]].mean()
df_summary_mpg_weight_horsepower

mpg       weight  horsepower
model year                                    
70          17.689655  3372.793103  147.827586
71          21.250000  2995.428571  106.535714
72          18.714286  3237.714286  120.178571
73          17.100000  3419.025000  130.475000
74          22.703704  2877.925926   94.185185
75          20.266667  3176.800000  101.066667
76          21.573529  3078.735294  101.117647
77          23.375000  2997.357143  105.071429
78          24.061111  2861.805556   99.694444
79          25.093103  3055.344828  101.206897
80          33.696552  2436.655172   78.551724
81          30.334483  2522.931034   81.448276
82          31.709677  2453.548387   81.838710

#### 9. Exporting Data Save a subset of the data containing only mpg, cylinders, horsepower, and weight for cars with mpg > 30 into a CSV fi le named high_mpg_cars.csv.

In [214]:
df_updated_dataset = df[df["mpg"] > 30][["mpg", "cylinders", "horsepower"]]
df_updated_dataset

mpg  cylinders  horsepower
53   31.0          4          65
54   35.0          4          69
129  31.0          4          67
131  32.0          4          65
144  31.0          4          52
..    ...        ...         ...
390  32.0          4          96
391  36.0          4          84
394  44.0          4          52
395  32.0          4          84
397  31.0          4          82

[85 rows x 3 columns]

In [216]:
new_df = df[df["mpg"] > 30][["mpg", "cylinders", "horsepower","weight"]]
new_df.to_csv("new_df.csv")

#### 10. Finding Anomalies Identify potential outliers in the mpg column using the Interquartile Range (IQR) method. Specifi cally:
● Calculate the IQR for mpg.
● Defi ne outliers as values less than Q1 - 1.5 * IQR or greater than Q3 + 1.5 * IQR.
● Create a DataFrame of cars classifi ed as outliers, displaying car_name, mpg, and model_year.
4

In [217]:
Q1=df['mpg'].quantile(0.25)
Q3=df['mpg'].quantile(0.75)
IQR = Q3-Q1

lower_bound=Q1 - 1.5 * IQR
upper_bound=Q3 + 1.5 * IQR



In [218]:
print(lower_bound)
print(upper_bound)

0.25
46.25


In [225]:
outliers = df[(df["mpg"]<lower_bound) | (df["mpg"]>upper_bound)]
outliers_df = outliers[['car name','mpg','model year']]

In [226]:
print("Outlier car is :")
outliers_df

Outlier car is :


car name   mpg  model year
322  mazda glc  46.6          80